### ISSUE TITLE
Cross validation failed

### ISSUE THREAD

**Issue by ludovicc** [LREN-CHUV/woken-validation#3]
Selected 
 Target var: subjectageyears
  Covars:  rightainsanteriorinsula leftpinsposteriorinsula rightstgsuperiortemporalgyrus

Run experiment with Anova, Linreg and KNN

[INFO] [11/30/2017 16:14:12.601] [woken-akka.actor.default-dispatcher-15] [akka.tcp://woken@hbpfedqa2.intranet.chuv:4090/user/$n/$c/$b] Received validation results for fold 0.
17/11/30 16:14:12 WARN SparkSession$Builder: Use an existing SparkSession, some configuration may not take effect.
[ERROR] [11/30/2017 16:14:12.608] [woken-akka.actor.default-dispatcher-15] [akka://woken/user/$n/$c/$b] Expected Double as JsNumber, but got "52"
spray.json.DeserializationException: Expected Double as JsNumber, but got "52"
	at spray.json.package$.deserializationError(package.scala:23)
	at spray.json.BasicFormats$DoubleJsonFormat$.read(BasicFormats.scala:55)
	at spray.json.BasicFormats$DoubleJsonFormat$.read(BasicFormats.scala:50)
	at spray.json.JsValue.convertTo(JsValue.scala:31)
	at eu.hbp.mip.woken.core.validation.RegressionScores$$anonfun$5.apply(Scores.scala:192)
	at eu.hbp.mip.woken.core.validation.RegressionScores$$anonfun$5.apply(Scores.scala:192)
	at scala.collection.immutable.List.map(List.scala:273)
	at eu.hbp.mip.woken.core.validation.RegressionScores.compute(Scores.scala:192)
	at eu.hbp.mip.woken.core.validation.Scores$.apply(Scores.scala:52)
	at eu.hbp.mip.woken.core.CrossValidationActor$$anonfun$6.applyOrElse(experiments.scala:449)
	at eu.hbp.mip.woken.core.CrossValidationActor$$anonfun$6.applyOrElse(experiments.scala:378)
	at scala.runtime.AbstractPartialFunction.apply(AbstractPartialFunction.scala:36)
	at akka.actor.FSM$class.processEvent(FSM.scala:604)
	at eu.hbp.mip.woken.core.CrossValidationActor.akka$actor$LoggingFSM$$super$processEvent(experiments.scala:323)
	at akka.actor.LoggingFSM$class.processEvent(FSM.scala:734)

**Comment by ludovicc** [comment]
I believe it's closed
